language: julia
os:
  - osx
  - linux
julia:
  - 1.1
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd());'
#   - julia -e 'Pkg.build("AffineInvariantMCMC"); Pkg.test("AffineInvariantMCMC"; coverage=true)'
after_success:
  - julia -e ''import Pkg; import AffineInvariantMCMC; cd(joinpath(dirname(pathof(AffineInvariantMCMC)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'